sudo: required # sets superuser permissions (required for docker)
services: # preinstalled services
  - docker 

before_install: # what happens before tests are run
  - docker build -t gregseed/docker-react -f Dockerfile.dev .

script: # contains all commands that supposed to run with test suite, watches for non-zero status codes
  - docker run -e CI=true gregseed/docker-react npm run test -- --coverage
  
deploy: # how to deploy application to aws (or other)
  provider: elasticbeanstalk # preconfigured
  region: "us-east-1" # region of deployment, in quotes
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-391970318800"
  bucket_path: "docker-react" # default name is the app name
  on:
    branch: master # only deploy on push to branch master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
